services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YourStrongPassword123!"
      POSTGRES_DB: "thepartybackdropdiva"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: thepartybackdropdiva.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=thepartybackdropdiva;Username=postgres;Password=YourStrongPassword123!
      - ASPNETCORE_ENVIRONMENT=Development
      - EmailSettings__SmtpServer=mailpit
    ports:
      - "5148:8080"
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started

  ui:
    build:
      context: ./thepartybackdropdiva-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
